### ISSUE TITLE
Fairy | Refactor dependabot to standards

### ISSUE THREAD

**Issue by tomerle** [gamitee-dev/html-fairy#380]
### Motivation
1. We need to apply our new standards on all repos.
2. This includes adding `github-actions`, which we're missing now, and currently behind with warnings.

### TODO 

```yml
version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    commit-message:
      prefix: "[dependabot]"

    # Intensity
    open-pull-requests-limit: 10
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    target-branch: develop
    versioning-strategy: increase
    commit-message:
      prefix: "[dependabot]"

    # Intensity
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
```
